CREATE OR REPLACE PROCEDURE AUTHDBACCESSPROC(IN DB_NAME VARCHAR(20), IN U_NAME VARCHAR(100), OUT RESULT1 VARCHAR(100))
LANGUAGE SQL
BEGIN
	GRANT CONNECT ON DATABASE TO USER U_NAME;
	SET RESULT1='USER AUTHORIZED';
END@