CREATE OR REPLACE PROCEDURE BALLSCPROC (IN MATCHNO INTEGER,IN PID INTEGER,IN WTAKEN INTEGER,IN TOVER INTEGER,IN RUNCN INTEGER)
BEGIN
DECLARE V_MATCHNO INTEGER;
DECLARE V_PID INTEGER;
DECLARE V_WTAKEN INTEGER;
DECLARE V_TOVER INTEGER;
DECLARE V_RUNCN INTEGER;
SET V_MATCHNO=MATCHNO;
SET V_PID = PID;
SET V_WTAKEN = WTAKEN;
SET V_TOVER = TOVER;
SET V_RUNCN = RUNCN;

INSERT INTO IPL.BALLSC VALUES (V_MATCHNO,V_PID,V_WTAKEN,V_TOVER,V_RUNCN);
END@
