CREATE OR REPLACE PROCEDURE BATSCPROC (IN MATCHNO INTEGER,IN PID INTEGER,IN BALLSPLAYED INTEGER,IN RUNS INTEGER,IN SIXS INTEGER, IN FOURS INTEGER, IN OUTBY VARCHAR(30), IN TYPEOFOUT VARCHAR(30), IN CAUGHTBY VARCHAR(30))
BEGIN
INSERT INTO IPL.BATSC VALUES (MATCHNO,PID,BALLSPLAYED,RUNS,SIXS,FOURS,OUTBY,TYPEOFOUT,CAUGHTBY);
END@

