CREATE OR REPLACE PROCEDURE BESTBOWLEROFTEAMPROC ()
DYNAMIC RESULT SETS 1
LANGUAGE SQL
BEGIN
	SELECT  P.NAME,P.TEAM_NAME, P.WTAKEN
	FROM (
   		SELECT TEAM_NAME, MAX(WTAKEN) as MOSTWICKETS
   		FROM IPL.PLAYER GROUP BY TEAM_NAME
	) AS X INNER JOIN IPL.PLAYER AS P ON P.TEAM_NAME = X.TEAM_NAME
	AND P.WTAKEN = X.MOSTWICKETS;
END@