CREATE OR REPLACE PROCEDURE BESTBATSMANOFTEAMPROC ()
DYNAMIC RESULT SETS 1
LANGUAGE SQL
BEGIN
	SELECT  P.NAME,P.TEAM_NAME, P.RUNS
	FROM (
   		SELECT TEAM_NAME, MAX(RUNS) as MOSTRUNS
   		FROM IPL.PLAYER GROUP BY TEAM_NAME
	) AS X INNER JOIN IPL.PLAYER AS P ON P.TEAM_NAME = X.TEAM_NAME
	AND P.RUNS = X.MOSTRUNS;
END@