CREATE OR REPLACE PROCEDURE BESTCATCHEROFTEAMPROC ()
DYNAMIC RESULT SETS 1
LANGUAGE SQL
BEGIN
	SELECT  P.NAME,P.TEAM_NAME, P.CATHCES
	FROM (
   		SELECT TEAM_NAME, MAX(CATCHES) as MOSTCATCHES
   		FROM IPL.PLAYER GROUP BY TEAM_NAME
	) AS X INNER JOIN IPL.PLAYER AS P ON P.TEAM_NAME = X.TEAM_NAME
	AND P.CATCHES = X.MOSTCATCHES;
END@