CREATE OR REPLACE PROCEDURE MOSTLIKEDPLAYEROFTEAMPROC (IN TEAM VARCHAR(30))
DYNAMIC RESULT SETS 1
LANGUAGE SQL
BEGIN
	DECLARE CURSOR1 CURSOR WITH RETURN FOR 
	SELECT  P.NAME,P.TEAM_NAME, P.LIKES
	FROM (
   		SELECT TEAM_NAME, MAX(LIKES) as MOSTLIKED
   		FROM IPL.PLAYER WHERE TEAM_NAME=TEAM GROUP BY TEAM_NAME
	) AS X INNER JOIN IPL.PLAYER AS P ON P.TEAM_NAME = X.TEAM_NAME
	AND P.LIKES = X.MOSTLIKED ORDER BY TEAM_NAME;
	OPEN CURSOR1;
END@