CREATE OR REPLACE PROCEDURE RESULTPROC (IN TEAMNAME VARCHAR(30), IN LOSER VARCHAR(30), IN MATCHNO INTEGER, IN STATUS VARCHAR(30), IN MANOFMATCH VARCHAR(30), IN WONBY VARCHAR(30), IN RUNMDBYWI INTEGER, IN RUNCNBYWI INTEGER, IN RUNMDBYLO INTEGER, IN RUNCNBYLO INTEGER, IN VROVERPLBYWI FLOAT(5), IN VROVERCNBYWI FLOAT(5), IN VROVERCNBYLO FLOAT(5), IN VROVERPLBYLO FLOAT(5))
BEGIN
INSERT INTO IPL.RESULT VALUES (TEAMNAME, LOSER, MATCHNO, STATUS, MANOFMATCH, WONBY, RUNMDBYWI, RUNCNBYWI, RUNMDBYLO, RUNCNBYLO, VROVERPLBYWI, VROVERCNBYWI, VROVERCNBYLO, VROVERPLBYLO);
END@

