CREATE OR REPLACE PROCEDURE TESTPROC(IN INP1 INTEGER, IN INP2 INTEGER, OUT RESULT1 INTEGER)
LANGUAGE SQL
BEGIN
	DECLARE V_PARAM1 INTEGER;
	DECLARE V_PARAM2 INTEGER;
	SET V_PARAM1=INP1;
	SET V_PARAM2=INP2;
	SET RESULT1=V_PARAM1+V_PARAM2;
END@