CREATE OR REPLACE PROCEDURE TICKETBOOKPROC (IN USERID VARCHAR(30),IN MATCHNO INTEGER,IN GROUND VARCHAR(40),IN PRICE INTEGER)
BEGIN

INSERT INTO IPL.TICKETBOOK  VALUES (USERID,MATCHNO,GROUND,PRICE);
END@