CREATE OR REPLACE PROCEDURE TOP3STRIKERATESPROC ()
DYNAMIC RESULT SETS 1
LANGUAGE SQL
BEGIN
	DECLARE STRIKERATES CURSOR WITH RETURN FOR 
	SELECT NAME,TEAM_NAME,STRR FROM IPL.PLAYER ORDER BY STRR DESC LIMIT 3;
	OPEN STRIKERATES;
END@