CREATE OR REPLACE PROCEDURE TOP3MAXSIXESPROC ()
DYNAMIC RESULT SETS 1
LANGUAGE SQL
BEGIN
	DECLARE MAXSIX CURSOR WITH RETURN FOR 
	SELECT NAME,TEAM_NAME,SIXS FROM IPL.PLAYER ORDER BY SIXS DESC LIMIT 3;
	OPEN MAXSIX;
END@