CREATE OR REPLACE PROCEDURE TOP3CATCHERSPROC ()
DYNAMIC RESULT SETS 1
LANGUAGE SQL
BEGIN
	DECLARE CATCHER CURSOR WITH RETURN FOR 
	SELECT NAME,TEAM_NAME,CATCHES FROM IPL.PLAYER ORDER BY CATCHES DESC LIMIT 3;
	OPEN CATCHER;
END@