CREATE OR REPLACE PROCEDURE TOP3TEAMS () 
    DYNAMIC RESULT SETS 1 
    LANGUAGE SQL 
    BEGIN 
        DECLARE result_set_1 CURSOR WITH RETURN  FOR
            SELECT NAME,NO_OF_MATCHES,WIN FROM IPL.TEAM ORDER BY WIN DESC LIMIT 3;    
        OPEN result_set_1;
    END@