CREATE OR REPLACE PROCEDURE TOP3MOSTFIFTIESPROC ()
DYNAMIC RESULT SETS 1
LANGUAGE SQL
BEGIN
	DECLARE MOSTFIFTIES CURSOR WITH RETURN FOR 
	SELECT NAME,TEAM_NAME,FIFTY FROM IPL.PLAYER ORDER BY FIFTY DESC LIMIT 3;
	OPEN MOSTFIFTIES;
END@