CREATE OR REPLACE PROCEDURE TOP3ECONOMYPROC ()
DYNAMIC RESULT SETS 1
LANGUAGE SQL
BEGIN
	DECLARE ECONOMY CURSOR WITH RETURN FOR 
	SELECT NAME,TEAM_NAME,ECON FROM IPL.PLAYER ORDER BY ECON DESC LIMIT 3;
	OPEN ECONOMY;
END@